### ISSUE TITLE
2 options to make the plugin easy to use on a PC.

### ISSUE THREAD

**Issue by a4jp-com** [leopuleo/easy-swipebox#1]
For a PC could you add these options:

Click overlay to close slideshow.
Click image to see next image.

I'm using the WordPress plugin.

Everything else is great. ^^

**Comment by leopuleo** [comment]
Hello @a4jp-com, 
thanks for your suggestions but the jquery functionalities and behaviours are managed by Swipebox (http://brutaldesign.github.io/swipebox/).

Any improvement/questions/requests related the jquery plugin to the should be submitted to this repository: https://github.com/brutaldesign/swipebox.

Thank you!
