### ISSUE TITLE
jQuery.isArray is deprecated; use Array.isArray

### ISSUE THREAD

**Issue by kadolino** [leopuleo/easy-swipebox#14]
/easy-swipebox/public/js/jquery.swipebox.min.js

for jquery 3.5.1 compatibility and WP 5.7

**Comment by leopuleo** [comment]
Hello @kadolino,
not sure to understand the issue, could you please provide more context?

Thank you

**Comment by kadolino** [comment]
Hello, the upcoming Wordpress 5.7 use jquery 3.5.1, which is not fully compatible to the old jquery 2.12.4, therefore the wordpress core team wrote a plugin jquery migration helper - this plugin generates this error messeage for easy-swipebox.

More context here:
https://github.com/jquery/jquery-migrate/blob/master/warnings.md

And here:
https://api.jquery.com/jQuery.isArray/
Quote: jQuery.isArray() - Note: This API has been deprecated in jQuery 3.2; please use the native Array.isArray method instead.

**Comment by leopuleo** [comment]
Thank you for posting the issue.
It has been solved with version [1.1.2](https://github.com/leopuleo/easy-swipebox/releases/tag/1.1.2) and it's available via Wordpress update.

I'm closing it, please feel free to re-open it in case of problems.
