### ISSUE TITLE
Image Init applies to anything with png/gif/jpg/etc in it

### ISSUE THREAD

**Issue by jas8522** [leopuleo/easy-swipebox#2]
The following link on my site is getting the swipebox class auto-assigned because it has the three letters 'gif' within it:

`<a href="/the-sparkling-starfish-jewellery-gifts/" class="swipebox"><span>The Sparkling Starfish Jewellery &amp; Gifts</span></a>`

Notice the word gifts? Your code for image detection in jquery.init.image.js on line 6 should be like this:

`return /(\.jpg|\.jpeg|\.gif|\.png)/i.test( $(this).attr('href'))`

**Comment by leopuleo** [comment]
Hello @jas8522, 
nice catch, I will test your solution in order to fix this bug soon!
Thank you!

**Comment by leopuleo** [comment]
New version 1.0.1 is out on WP repo
Please let me know if everything works fine.
Thank you again!

**Comment by jas8522** [comment]
That's great, thanks for the quick update!

My fix may not be the best solution though. It's possible that a link href could contain something like:

/lemon.gifts.are.great/ which I think would still wind up getting the class applied when it shouldn't. It might be better to have it like this to indicate that the end of href string immediately follows the file extension:
`/(\.jpg|\.jpeg|\.gif|\.png)$/`

The only possible issue with that is if someone tries to use a query string, but I suspect that's their own problem for doing weird stuff with links? ;)

For example, this would not be detected properly: /myimage.gif?size=1280x800

But then to even have that work you'd need some major modifications wherein .gif files are forcefully processed by PHP or something like that. So it might be such an edge case that it doesn't matter.
