### ISSUE TITLE
Lengthen the hide bars delay

### ISSUE THREAD

**Issue by MelR** [leopuleo/easy-swipebox#5]
Thanks for putting this together as a plugin! I would like to lengthen the delay of the bars from 3 seconds to 10 seconds, maybe longer. I see this is a Swipebox option. Could this be added as a form to the Easy SwipeBox settings page to allow control of the delay? Control over other options (videoMaxWidth, loopAtEnd, etc) from the settings page  would be a nice addition as well.

hideBarsDelay : 3000, // delay before hiding bars on desktop

**Comment by leopuleo** [comment]
Hi @MelR,
thanks for your suggestion.
With version 1.0 I introduce the setting page and this will be integrated with new configurations in future versions.
I will keep you up to date! :smile:

**Comment by leopuleo** [comment]
Hi @MelR ,
Please check the new version 1.1.0.
New setting page for Lightbox settings where you can control all the SwipeBox options.

Enjoy it and please let me know if you have any problem using it.
